# Generated by Django 5.2.8 on 2025-11-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='assigned_vehicle',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='completed',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
