# Generated by Django 5.2.8 on 2025-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rename_created_at_riderequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='transport_type',
            field=models.CharField(choices=[('taxi', 'Taxi'), ('bike', 'Bike')], default='taxi', max_length=16),
        ),
    ]
