# Generated by Django 5.2.8 on 2025-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('taxi', 'Taxi'), ('bike', 'Bike')], max_length=16),
        ),
    ]
