# Generated by Django 5.2.8 on 2025-11-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('nin', 'National ID (NIN)'), ('passport', 'Passport')], max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_driver_approved',
            field=models.BooleanField(default=False),
        ),
    ]
